import i18n from 'i18next';
import { initReactI18next } from 'react-i18next';

const resources = {
  en: {
    translation: {
      "nav_home": "Home",
      "nav_about": "About",
      "nav_programs": "Programs",
      "nav_projects": "Projects",
      "nav_contact": "Contact",
      "nav_apply": "Apply Now",
      "footer_desc": "A premier multidisciplinary engineering institution preparing the next generation of software, hardware, robotics, and AI engineers.",
      "footer_location": "San Francisco, CA",
      "footer_rights": "© 2026 Engineering Academy. All rights reserved.",
      "testi_title": "What Our Engineers Say",
      "testi_subtitle": "Success stories from alumni now working at leading tech companies",
      "testi_sarah_role": "Software Engineer",
      "testi_sarah_text": "The hands-on projects and expert mentorship gave me the confidence to transition into a senior engineering role.",
      "testi_marcus_role": "Backend Developer",
      "testi_marcus_text": "Best investment in my career. The curriculum is exactly what you need to build production systems.",
      "testi_aisha_role": "Full-Stack Engineer",
      "testi_aisha_text": "From zero to deploying real applications in months. The quality of instruction is unmatched.",
      "journey_title": "The Engineering Journey",
      "journey_subtitle": "A structured path from beginner to professional software engineer",
      "step_learn_title": "Learn Fundamentals",
      "step_learn_desc": "Master core programming concepts, data structures, and algorithms with expert guidance.",
      "step_build_sys_title": "Build Real Systems",
      "step_build_sys_desc": "Apply your knowledge by developing production-grade applications and infrastructure.",
      "step_collab_team_title": "Collaborate in Teams",
      "step_collab_team_desc": "Work on group projects using industry-standard tools like Git, Jira, and Slack.",
      "step_deploy_proj_title": "Deploy Projects",
      "step_deploy_proj_desc": "Ship your applications to the cloud and experience the full development lifecycle.",
      "step_career_supp_title": "Career Support",
      "step_career_supp_desc": "Get resume reviews, mock interviews, and direct introductions to hiring partners.",
      "phil_mission": "Our Mission",
      "phil_title": "Engineering Philosophy",
      "phil_desc1": "We believe engineering is more than writing code or designing circuits. It's a mindset — a systematic approach to understanding complexity, creating solutions, and building the future.",
      "phil_desc2": "At Engineering Academy, we prepare students to become the architects of tomorrow's technology, combining deep technical mastery with creative problem-solving and interdisciplinary collaboration.",
      "phil_cta_title": "Join the Next Generation of Engineers",
      "phil_cta_desc": "Whether you're passionate about software, electronics, robotics, or AI — we'll help you transform that passion into world-class engineering expertise.",
      "phil_btn_apply": "Apply Now",
      "phil_btn_download": "Download Curriculum",
      "prin_think_title": "Think Like Engineers",
      "prin_think_desc": "Develop systematic problem-solving, critical thinking, and first-principles reasoning.",
      "prin_build_title": "Build Production Systems",
      "prin_build_desc": "Create real-world solutions that meet industrial standards and professional requirements.",
      "prin_integrate_title": "Integrate Hardware + Software",
      "prin_integrate_desc": "Master the complete engineering stack from embedded firmware to cloud infrastructure.",
      "prin_solve_title": "Solve Real Problems",
      "prin_solve_desc": "Work on projects that matter, addressing actual technical challenges and industry needs.",
      "prin_collab_title": "Collaborate Across Disciplines",
      "prin_collab_desc": "Experience multidisciplinary teamwork mirroring modern engineering organizations.",
      "prin_innovate_title": "Drive Innovation",
      "prin_innovate_desc": "Push boundaries, experiment with emerging technologies, and shape the future.",
      "title": "Engineering Disciplines",
      "description": "Master the complete spectrum of modern engineering — from software and electronics to robotics, AI, and advanced hardware systems.",
      "explore": "Explore Program",
      "overview": "Detailed Program Overview",
      "about": "About the Program",
      "technologies": "Key Technologies",
      "close": "Close",
      "software_title": "Software Engineering",
      "software_desc": "Full-stack systems, backend architecture, cloud infrastructure, AI systems, and distributed computing at scale.",
      "software_details": "In this program, you will explore scalable system design, database management, microservices architecture, and modern frameworks.",
      "electrical_title": "Electrical Engineering",
      "electrical_desc": "Analog & digital electronics, PCB design, signal processing, power systems, and circuit architecture.",
      "electrical_details": "This program covers the complete lifecycle of electronics creation: from circuit simulation in SPICE to multi-layer PCB routing.",
      "mechanical_title": "Mechanical Engineering",
      "mechanical_desc": "CAD systems, robotics mechanics, manufacturing, thermodynamics, and aerospace engineering principles.",
      "mechanical_details": "Master the principles of mechanism design, Finite Element Analysis (FEA), thermodynamics, and modern manufacturing methods.",
      "embedded_title": "Embedded & Hardware",
      "embedded_desc": "STM32, microcontrollers, FPGA systems, IoT devices, firmware development, and sensor integration.",
      "embedded_details": "Dive into bare-metal microcontroller programming in C/C++, work with Real-Time Operating Systems (RTOS), and design custom FPGA architectures.",
      "robotics_title": "Robotics Engineering",
      "robotics_desc": "Autonomous systems, motion control, computer vision, sensor fusion, and AI-powered robotics.",
      "robotics_details": "Learn how to bring machines to life. The program includes studying the Robot Operating System (ROS), kinematics, and processing data.",
      "ai_title": "AI Engineering",
      "ai_desc": "Machine learning, deep learning, LLMs, computer vision, NLP, and production AI systems.",
      "ai_details": "Master neural network training architectures, work extensively with Large Language Models (LLMs) and computer vision.",
      "systems_title": "Systems Engineering",
      "systems_desc": "Complex system design, integration, architecture, verification, and large-scale engineering projects.",
      "systems_details": "Learn to see the big picture: from comprehensive requirements management to cross-disciplinary subsystem integration.",
      "hardware_title": "Hardware Engineering",
      "hardware_desc": "Custom silicon design, hardware prototyping, manufacturing, testing, and product engineering.",
      "hardware_details": "Take projects from concept to finished device. Design custom silicon (ASIC), create rapid hardware prototypes, and conduct rigorous testing.",
      "contact_title": "Start Your Journey",
      "contact_subtitle": "Apply now or reach out to learn more about our programs",
      "contact_name_label": "Full Name",
      "contact_name_placeholder": "John Doe",
      "contact_email_label": "Email Address",
      "contact_email_placeholder": "john@example.com",
      "contact_goals_label": "Your Goals & Background",
      "contact_goals_placeholder": "Tell us about your programming experience and career goals...",
      "contact_submit": "Submit Application",
      "contact_or_google": "Or register directly via Google Form",
      "contact_google_btn": "Open Registration Form",
      "contact_or_direct": "Connect with us directly",
      "contact_telegram": "Telegram",
      "contact_whatsapp": "WhatsApp",
      "about_title": "Built for Future Engineers",
      "about_p1": "Engineering Academy was created for ambitious students who want more than theoretical tutorials. We focus on deep engineering thinking, real-world systems, and production-grade development skills.",
      "about_p2": "Our programs are designed to simulate real software engineering environments — combining computer science fundamentals, modern technologies, and collaborative project building.",
      "about_p3": "We partner with industry leaders to ensure our curriculum reflects the actual demands of professional software development. Every instructor is a practicing engineer with years of production experience.",
      "about_p4": "We don't just teach code. We build engineers.",
      "modal_outcomes": "Career Outcomes",
      "modal_curriculum": "Curriculum Timeline",
      "modal_enroll": "Enroll in This Course",
      "prog_title": "Engineering Programs",
      "prog_subtitle": "Specialized tracks designed to transform you into an expert in your chosen domain",
      "prog_register": "Register Now",
      "prog_syllabus": "View Syllabus",
      "course_javascript_title": "JavaScript Engineering",
      "course_javascript_dur": "8-9 months",
      "course_javascript_desc": "Master modern JavaScript, from core concepts and ES6+ to advanced DOM manipulation and Web APIs.",
      "course_fullstack_title": "Full-Stack Systems",
      "course_fullstack_dur": "20 Weeks",
      "course_fullstack_desc": "Master the complete stack from database design to deployment and everything in between.",
      "course_devhack_title": "DevHack",
      "course_devhack_dur": "15 months",
      "course_devhack_desc": "Learn infrastructure as code, container orchestration, and modern deployment pipelines.",
      "course_embedded_title": "Embedded Systems",
      "course_embedded_dur": "18 Weeks",
      "course_embedded_desc": "Develop firmware and IoT solutions for hardware devices and embedded platforms.",
      "course_ai_title": "AI Engineering",
      "course_ai_dur": "12-14 months",
      "course_ai_desc": "Build intelligent applications with machine learning, LLMs, and AI-powered systems.",
      "course_software_title": "Software Engineering",
      "course_software_dur": "9 Months",
      "course_software_desc": "Master software engineering principles, SDLC, design patterns, testing, and agile methodologies.",
      "course_mechanical_title": "Mechanical Engineering",
      "course_mechanical_dur": "12-15 Weeks",
      "course_mechanical_desc": "Master the fundamentals of mechanical design, thermodynamics, materials science, and modern CAD software.",
      "course_microcontroller_title": "Microcontroller Fundamentals",
      "course_microcontroller_dur": "14-16 Weeks",
      "course_microcontroller_desc": "Dive into bare-metal programming, memory management, and peripheral interfacing for microcontrollers.",
      "course_electrical_title": "Electrical Engineering",
      "course_electrical_dur": "8 months",
      "course_electrical_desc": "Explore advanced circuit analysis, analog and digital electronics, signal processing, and power systems.",
      "course_digital_logic_title": "Digital Logic Design",
      "course_digital_logic_dur": "12 Weeks",
      "course_digital_logic_desc": "Learn the foundations of digital hardware, from boolean algebra to building complex sequential circuits.",
      "course_fpga_title": "FPGA Engineering",
      "course_fpga_dur": "2 months",
      "course_fpga_desc": "Design, simulate, and implement high-performance custom digital hardware using FPGAs.",
      "course_hardware_title": "Hardware Engineering",
      "course_hardware_dur": "16 Weeks",
      "course_hardware_desc": "Master the complete hardware product lifecycle, from schematic capture and PCB routing to manufacturing.",
      "how_title": "How We Teach",
      "how_subtitle": "Our methodology combines theoretical foundations with intensive practical experience, mirroring how professional engineers work in leading tech companies",
      "step_theory_title": "Learn Core Theory",
      "step_theory_desc": "Master fundamental concepts through expert-led lectures, reading materials, and interactive workshops.",
      "step_labs_title": "Practice with Labs",
      "step_labs_desc": "Apply knowledge in guided coding labs with immediate feedback and hands-on exercises.",
      "step_build_title": "Build Real Systems",
      "step_build_desc": "Develop production-grade applications using industry-standard tools and best practices.",
      "step_collab_title": "Collaborate in Teams",
      "step_collab_desc": "Work in agile teams using Git, code reviews, and professional development workflows.",
      "step_deploy_title": "Deploy Production Projects",
      "step_deploy_desc": "Ship applications to the cloud, experiencing the complete software development lifecycle.",
      "step_career_title": "Prepare for Industry Careers",
      "step_career_desc": "Get resume support, mock interviews, and direct connections to our hiring partner network.",
      "labs_badge": "Research-Grade Infrastructure",
      "labs_title": "Labs & Facilities",
      "labs_subtitle": "State-of-the-art laboratories and engineering workspaces designed for innovation, collaboration, and breakthrough technical development",
      "labs_footer_text": "All students gain 24/7 access to professional-grade equipment and facilities",
      "labs_btn_tour": "Schedule a Lab Tour",
      "hero_title_1": "Build the Future",
      "hero_title_2": "Through Engineering",
      "hero_desc": "From software and AI to electronics, robotics, and advanced hardware systems — Engineering Academy prepares the next generation of world-class engineers.",
      "hero_btn_join": "Join the Next Cohort",
      "hero_btn_explore": "Explore Curriculum",
      "hero_console_ready": "Systems ready",
      "metric_engineers": "Engineers Trained",
      "metric_disciplines": "Disciplines",
      "metric_projects": "Projects Built",
      "metric_placement": "Placement Rate",
      "showcase_title": "Multidisciplinary Projects",
      "showcase_subtitle": "Real engineering systems built by our students — spanning software, hardware, robotics, AI, and embedded systems",
      "proj_robot_title": "Autonomous Delivery Robot",
      "proj_robot_cat": "Robotics + AI",
      "proj_iot_title": "Smart IoT Energy System",
      "proj_iot_cat": "Embedded + Hardware",
      "proj_dashboard_title": "AI-Powered Dashboard",
      "proj_dashboard_cat": "Software + AI",
      "proj_drone_title": "Drone Flight Controller",
      "proj_drone_cat": "Embedded + Robotics",
      "proj_monitor_title": "Industrial Monitoring Platform",
      "proj_monitor_cat": "Systems Engineering",
      "proj_fpga_title": "Custom FPGA Processor",
      "proj_fpga_cat": "Hardware Engineering",
      "proj_arm_title": "Robotic Arm Controller",
      "proj_arm_cat": "Mechanical + Software",
      "proj_hub_title": "Smart Home Hub",
      "proj_hub_cat": "Electrical + IoT",
      "proj_chat_title": "LLM Chat Application",
      "proj_chat_cat": "AI Engineering",
      "why_title": "Why Choose Us",
      "why_subtitle": "A comprehensive approach to engineering education that prepares you for the real world",
      "feat_curriculum_title": "Intensive Curriculum",
      "feat_curriculum_desc": "Industry-aligned courses designed by senior engineers to build production-ready skills through hands-on practice.",
      "feat_projects_title": "Real-world Projects",
      "feat_projects_desc": "Build and deploy actual systems, from distributed backends to AI platforms, gaining portfolio-worthy experience.",
      "feat_mentors_title": "Expert Mentors",
      "feat_mentors_desc": "Learn from experienced engineers at leading tech companies who provide personalized guidance and code reviews.",
      "lab_ai_name": "AI Computing Lab",
      "lab_ai_desc": "High-performance GPU clusters for deep learning, LLM fine-tuning, and advanced AI research.",
      "lab_robotics_name": "Robotics Laboratory",
      "lab_robotics_desc": "Industrial robotic arms, autonomous vehicles, drones, and motion capture systems for robotics development.",
      "lab_electronics_name": "Electronics Lab",
      "lab_electronics_desc": "Oscilloscopes, signal generators, PCB fabrication, and precision measurement equipment.",
      "lab_embedded_name": "Embedded Systems",
      "lab_embedded_desc": "STM32, FPGA dev boards, logic analyzers, and IoT prototyping workstations.",
      "lab_mechanical_name": "Mechanical Workshop",
      "lab_mechanical_desc": "3D printers, CNC machines, CAD workstations, and precision manufacturing tools.",
      "lab_studios_name": "Collaborative Studios",
      "lab_studios_desc": "Team project spaces with whiteboards, video conferencing, and agile development tools.",
      "how_cta_title": "Experience the Engineering Academy Difference",
      "how_cta_desc": "Our proven methodology has helped over 150 students transition into successful engineering careers at companies like Google, Meta, Amazon, and innovative startups worldwide.",
      "how_cta_btn": "Start Your Journey Today",
      "val_exc_title": "Engineering Excellence",
      "val_exc_desc": "We believe in deep technical mastery, not surface-level tutorials. Every lesson builds real engineering thinking.",
      "val_prod_title": "Production-First Learning",
      "val_prod_desc": "Students work on real systems from day one, experiencing the full software development lifecycle.",
      "val_inno_title": "Innovation-Driven",
      "val_inno_desc": "We teach the latest technologies and methodologies used by leading tech companies worldwide.",
      "val_cult_title": "Collaborative Culture",
      "val_cult_desc": "Team projects, code reviews, and pair programming mirror professional engineering environments."
    }
  },
  ru: {
    translation: {
      "nav_home": "Главная",
      "nav_about": "О нас",
      "nav_programs": "Программы",
      "nav_projects": "Проекты",
      "nav_contact": "Контакты",
      "nav_apply": "Подать заявку",
      "footer_desc": "Ведущее многопрофильное инженерное учебное заведение, готовящее новое поколение инженеров в сфере ПО, аппаратного обеспечения, робототехники и ИИ.",
      "footer_location": "Сан-Франциско, Калифорния",
      "footer_rights": "© 2026 Инженерная Академия. Все права защищены.",
      "testi_title": "Что говорят наши инженеры",
      "testi_subtitle": "Истории успеха выпускников, которые теперь работают в ведущих IT-компаниях",
      "testi_sarah_role": "Инженер-программист",
      "testi_sarah_text": "Практические проекты и экспертное наставничество дали мне уверенность для перехода на позицию Senior-инженера.",
      "testi_marcus_role": "Backend-разработчик",
      "testi_marcus_text": "Лучшая инвестиция в моей карьере. Программа — это именно то, что нужно для создания production-систем.",
      "testi_aisha_role": "Full-Stack инженер",
      "testi_aisha_text": "От нуля до развертывания реальных приложений за несколько месяцев. Качество обучения не имеет себе равных.",
      "journey_title": "Инженерный путь",
      "journey_subtitle": "Структурированный путь от новичка до профессионального инженера-программиста",
      "step_learn_title": "Изучение основ",
      "step_learn_desc": "Освойте базовые концепции программирования, структуры данных и алгоритмы под руководством экспертов.",
      "step_build_sys_title": "Создание реальных систем",
      "step_build_sys_desc": "Применяйте знания, разрабатывая приложения и инфраструктуру уровня продакшен.",
      "step_collab_team_title": "Командное взаимодействие",
      "step_collab_team_desc": "Работайте над групповыми проектами, используя стандартные для индустрии инструменты: Git, Jira и Slack.",
      "step_deploy_proj_title": "Запуск проектов",
      "step_deploy_proj_desc": "Разворачивайте свои приложения в облаке и проходите полный цикл разработки.",
      "step_career_supp_title": "Карьерная поддержка",
      "step_career_supp_desc": "Получите разбор резюме, пройдите тестовые собеседования и выйдите напрямую на партнеров по найму.",
      "hero_title_1": "Создавайте будущее",
      "hero_title_2": "С помощью инженерии",
      "hero_desc": "От софта и ИИ до электроники, робототехники и передовых аппаратных систем — Инженерная Академия готовит новое поколение инженеров мирового класса.",
      "hero_btn_join": "Присоединиться к потоку",
      "hero_btn_explore": "Изучить программу",
      "hero_console_ready": "Системы готовы",
      "about_title": "Создано для будущих инженеров",
      "about_p1": "Инженерная Академия создана для амбициозных студентов, которым нужно больше, чем просто теоретические туториалы. Мы делаем упор на глубокое инженерное мышление, реальные системы и навыки разработки уровня продакшена.",
      "about_p2": "Наши программы разработаны так, чтобы имитировать реальную среду разработки ПО — объединяя основы информатики, современные технологии и совместное создание проектов.",
      "about_p3": "Мы сотрудничаем с лидерами индустрии, чтобы наша программа отражала реальные требования профессиональной разработки. Каждый преподаватель — действующий инженер с многолетним опытом работы в продакшене.",
      "about_p4": "Мы не просто учим писать код. Мы создаем инженеров.",
      "modal_outcomes": "Карьерные перспективы",
      "modal_curriculum": "Программа курса",
      "modal_enroll": "Записаться на курс",
      "prog_title": "Инженерные программы",
      "prog_subtitle": "Специализированные направления, которые сделают из вас эксперта в выбранной области",
      "prog_register": "Зарегистрироваться",
      "prog_syllabus": "Смотреть программу",
      "course_javascript_title": "JavaScript-разработка",
      "course_javascript_dur": "8-9 месяцев",
      "course_javascript_desc": "Освойте современный JavaScript: от базовых концепций и ES6+ до продвинутой работы с DOM и Web API.",
      "course_fullstack_title": "Full-Stack системы",
      "course_fullstack_dur": "20 недель",
      "course_fullstack_desc": "Освойте полный стек технологий: от проектирования баз данных до деплоя.",
      "course_devhack_title": "DevHack",
      "course_devhack_dur": "15 месяцев",
      "course_devhack_desc": "Изучите инфраструктуру как код, оркестрацию контейнеров и современные пайплайны развертывания.",
      "course_embedded_title": "Встраиваемые системы",
      "course_embedded_dur": "18 недель",
      "course_embedded_desc": "Разрабатывайте прошивки и IoT-решения для аппаратных устройств и платформ.",
      "course_ai_title": "Инженерия ИИ (AI)",
      "course_ai_dur": "12-14 месяцев",
      "course_ai_desc": "Создавайте интеллектуальные приложения с использованием машинного обучения и LLM.",
      "course_software_title": "Программная инженерия",
      "course_software_dur": "16 недель",
      "course_software_desc": "Освойте принципы инженерии ПО, жизненный цикл разработки, паттерны проектирования и agile-методологии.",
      "course_mechanical_title": "Машиностроение",
      "course_mechanical_dur": "12-15 недель",
      "course_mechanical_desc": "Освойте основы проектирования механизмов, термодинамики, материаловедения и современных CAD-систем.",
      "course_microcontroller_title": "Основы микроконтроллеров",
      "course_microcontroller_dur": "14-16 недель",
      "course_microcontroller_desc": "Погрузитесь в bare-metal программирование, управление памятью и работу с периферией микроконтроллеров.",
      "course_electrical_title": "Электротехника",
      "course_electrical_dur": "8 месяцев",
      "course_electrical_desc": "Изучите продвинутый анализ цепей, аналоговую и цифровую электронику, обработку сигналов и энергосистемы.",
      "course_digital_logic_title": "Цифровая логика",
      "course_digital_logic_dur": "12 недель",
      "course_digital_logic_desc": "Изучите основы цифровой аппаратуры: от булевой алгебры до создания последовательных цепей.",
      "course_fpga_title": "Инженерия FPGA",
      "course_fpga_dur": "2 месяца",
      "course_fpga_desc": "Проектируйте, симулируйте и реализуйте высокопроизводительную цифровую аппаратуру с использованием FPGA.",
      "course_hardware_title": "Аппаратная инженерия",
      "course_hardware_dur": "16 недель",
      "course_hardware_desc": "Освойте полный жизненный цикл создания оборудования: от схемотехники и трассировки PCB до производства.",
      "how_title": "Как мы обучаем",
      "how_subtitle": "Наша методология сочетает теоретическую базу с интенсивной практикой, повторяя рабочие процессы профессиональных инженеров в ведущих IT-компаниях.",
      "step_theory_title": "Изучение базовой теории",
      "step_theory_desc": "Освойте фундаментальные концепции через лекции от экспертов, материалы для чтения и интерактивные воркшопы.",
      "step_labs_title": "Практика в лабораториях",
      "step_labs_desc": "Применяйте знания в пошаговых лабораторных работах с мгновенной обратной связью и практическими упражнениями.",
      "step_build_title": "Создание реальных систем",
      "step_build_desc": "Разрабатывайте приложения уровня продакшен, используя стандартные для индустрии инструменты и лучшие практики.",
      "step_collab_title": "Командное взаимодействие",
      "step_collab_desc": "Работайте в agile-командах, используя Git, код-ревью и профессиональные процессы разработки.",
      "step_deploy_title": "Запуск проектов в продакшен",
      "step_deploy_desc": "Разворачивайте приложения в облаке, проходя полный жизненный цикл разработки программного обеспечения.",
      "step_career_title": "Подготовка к карьере",
      "step_career_desc": "Получите помощь с резюме, пройдите тестовые собеседования и выйдите напрямую на наших партнеров по найму.",
      "contact_title": "Начните свой путь",
      "contact_subtitle": "Подайте заявку или свяжитесь с нами, чтобы узнать больше о программах",
      "contact_name_label": "Полное имя",
      "contact_name_placeholder": "Иван Иванов",
      "contact_email_label": "Электронная почта",
      "contact_email_placeholder": "ivan@example.com",
      "contact_goals_label": "Ваши цели и опыт",
      "contact_goals_placeholder": "Расскажите о своем опыте программирования и карьерных целях...",
      "contact_submit": "Отправить заявку",
      "contact_or_google": "Или зарегистрируйтесь через Google Форму",
      "contact_google_btn": "Открыть форму регистрации",
      "contact_or_direct": "Свяжитесь с нами напрямую",
      "contact_telegram": "Telegram",
      "contact_whatsapp": "WhatsApp",
      "showcase_title": "Мультидисциплинарные проекты",
      "showcase_subtitle": "Реальные инженерные системы, созданные нашими студентами — от софта и аппаратного обеспечения до робототехники, ИИ и встроенных систем",
      "proj_robot_title": "Автономный робот-доставщик",
      "proj_robot_cat": "Робототехника + ИИ",
      "proj_iot_title": "Умная IoT-система энергоснабжения",
      "proj_iot_cat": "Встраиваемые системы + Железо",
      "proj_dashboard_title": "Дашборд на базе ИИ",
      "proj_dashboard_cat": "Софт + ИИ",
      "proj_drone_title": "Контроллер полета дрона",
      "proj_drone_cat": "Встраиваемые системы + Робототехника",
      "proj_monitor_title": "Платформа промышленного мониторинга",
      "proj_monitor_cat": "Системная инженерия",
      "proj_fpga_title": "Пользовательский FPGA-процессор",
      "proj_fpga_cat": "Аппаратная инженерия",
      "proj_arm_title": "Контроллер роботизированной руки",
      "proj_arm_cat": "Механика + Софт",
      "proj_hub_title": "Хаб умного дома",
      "proj_hub_cat": "Электроника + IoT",
      "proj_chat_title": "LLM Чат-приложение",
      "proj_chat_cat": "Инженерия ИИ",
      "metric_engineers": "Обученных инженеров",
      "metric_disciplines": "Направлений",
      "metric_projects": "Созданных проектов",
      "metric_placement": "Трудоустроено",
      "labs_badge": "Инфраструктура исследовательского уровня",
      "labs_title": "Лаборатории и оборудование",
      "labs_subtitle": "Современные лаборатории и инженерные рабочие пространства, созданные для инноваций, сотрудничества и прорывных технических разработок.",
      "labs_footer_text": "Все студенты получают круглосуточный (24/7) доступ к профессиональному оборудованию и лабораториям.",
      "labs_btn_tour": "Записаться на экскурсию",
      "lab_ai_name": "Лаборатория ИИ-вычислений",
      "lab_ai_desc": "Высокопроизводительные GPU-кластеры для глубокого обучения, дообучения LLM и передовых исследований в области ИИ.",
      "lab_robotics_name": "Лаборатория робототехники",
      "lab_robotics_desc": "Промышленные роботизированные манипуляторы, автономные автомобили, дроны и системы захвата движения.",
      "lab_electronics_name": "Лаборатория электроники",
      "lab_electronics_desc": "Осциллографы, генераторы сигналов, производство печатных плат и высокоточное измерительное оборудование.",
      "lab_embedded_name": "Встраиваемые системы",
      "lab_embedded_desc": "Отладочные платы STM32 и FPGA, логические анализаторы и рабочие станции для прототипирования IoT.",
      "lab_mechanical_name": "Механическая мастерская",
      "lab_mechanical_desc": "3D-принтеры, станки с ЧПУ, CAD-станции и инструменты для высокоточного производства.",
      "lab_studios_name": "Студии совместной работы",
      "lab_studios_desc": "Пространства для командных проектов с маркерными досками, видеосвязью и инструментами agile-разработки.",
      "phil_mission": "Наша миссия",
      "phil_title": "Инженерная философия",
      "phil_desc1": "Мы верим, что инженерия — это нечто большее, чем написание кода или проектирование схем. Это мышление — системный подход к пониманию сложности, созданию решений и построению будущего.",
      "phil_desc2": "В Инженерной Академии мы готовим студентов стать архитекторами технологий завтрашнего дня, объединяя глубокое техническое мастерство с творческим решением проблем и междисциплинарным сотрудничеством.",
      "phil_cta_title": "Присоединяйтесь к новому поколению инженеров",
      "phil_cta_desc": "Независимо от того, увлекаетесь ли вы программированием, электроникой, робототехкой или ИИ — мы поможем вам превратить эту страсть в инженерный опыт мирового уровня.",
      "phil_btn_apply": "Подать заявку",
      "phil_btn_download": "Скачать программу",
      "why_title": "Почему выбирают нас",
      "why_subtitle": "Комплексный подход к инженерному образованию, который готовит вас к реальной работе",
      "feat_curriculum_title": "Интенсивная программа",
      "feat_curriculum_desc": "Курсы, ориентированные на индустрию и разработанные старшими инженерами для формирования практических навыков.",
      "feat_projects_title": "Реальные проекты",
      "feat_projects_desc": "Создавайте и запускайте реальные системы, от распределенных бэкендов до ИИ-платформ, собирая мощное портфолио.",
      "feat_mentors_title": "Опытные менторы",
      "feat_mentors_desc": "Обучайтесь у опытных инженеров из ведущих IT-компаний, получая персональные советы и код-ревью.",
      "prin_think_title": "Думай как инженер",
      "prin_think_desc": "Развивайте системное решение проблем, критическое мышление и логику от первых принципов.",
      "prin_build_title": "Создавай production-системы",
      "prin_build_desc": "Создавайте реальные решения, соответствующие промышленным стандартам и профессиональным требованиям.",
      "prin_integrate_title": "Объединяй софт и железо",
      "prin_integrate_desc": "Освойте полный инженерный стек: от встроенных прошивок до облачной инфраструктуры.",
      "prin_solve_title": "Решай реальные задачи",
      "prin_solve_desc": "Работайте над значимыми проектами, решая актуальные технические и отраслевые проблемы.",
      "prin_collab_title": "Междисциплинарное сотрудничество",
      "prin_collab_desc": "Получите опыт работы в многопрофильных командах, как в современных инженерных компаниях.",
      "prin_innovate_title": "Внедряй инновации",
      "prin_innovate_desc": "Раздвигайте границы, экспериментируйте с новейшими технологиями и формируйте будущее.",
      "how_cta_title": "Почувствуйте разницу Инженерной Академии",
      "how_cta_desc": "Наша проверенная методология помогла более чем 150 студентам успешно начать карьеру инженеров в таких компаниях, как Google, Meta, Amazon и инновационных стартапах по всему миру.",
      "how_cta_btn": "Начните свой путь сегодня",
      "val_exc_title": "Инженерное превосходство",
      "val_exc_desc": "Мы верим в глубокое техническое мастерство, а не в поверхностные туториалы. Каждый урок формирует реальное инженерное мышление.",
      "val_prod_title": "Обучение через продакшен",
      "val_prod_desc": "Студенты работают над реальными системами с первого дня, проходя полный жизненный цикл разработки ПО.",
      "val_inno_title": "Инновационный подход",
      "val_inno_desc": "Мы преподаем новейшие технологии и методологии, используемые ведущими мировыми IT-компаниями.",
      "val_cult_title": "Культура сотрудничества",
      "val_cult_desc": "Командные проекты, ревью кода и парное программирование отражают профессиональную инженерную среду.",
      "title": "Инженерные дисциплины",
      "description": "Освойте полный спектр современной инженерии — от программирования и электроники до робототехники, ИИ и аппаратных систем.",
      "explore": "Изучить программу",
      "overview": "Детальный обзор",
      "about": "О программе",
      "technologies": "Ключевые технологии",
      "close": "Закрыть",
      "software_title": "Программная инженерия",
      "software_desc": "Фуллстек системы, бэкенд архитектура, облачная инфраструктура, системы ИИ и распределенные вычисления.",
      "software_details": "В этой программе вы изучите масштабируемое проектирование систем, управление базами данных и микросервисную архитектуру.",
      "electrical_title": "Электротехника",
      "electrical_desc": "Аналоговая и цифровая электроника, дизайн печатных плат (PCB), обработка сигналов и энергосистемы.",
      "electrical_details": "Полный цикл создания электроники: от симуляции цепей в SPICE до разводки многослойных печатных плат.",
      "mechanical_title": "Машиностроение",
      "mechanical_desc": "CAD системы, механика роботов, производство, термодинамика и принципы аэрокосмической инженерии.",
      "mechanical_details": "Освойте принципы проектирования механизмов, расчет методом конечных элементов (FEA) и современные методы производства.",
      "embedded_title": "Встраиваемые системы",
      "embedded_desc": "STM32, микроконтроллеры, FPGA системы, IoT устройства, разработка прошивок и интеграция сенсоров.",
      "embedded_details": "Погрузитесь в программирование микроконтроллеров на C/C++, работу с RTOS и проектирование FPGA архитектур.",
      "robotics_title": "Робототехника",
      "robotics_desc": "Автономные системы, управление движением, компьютерное зрение, объединение датчиков и ИИ-робототехника.",
      "robotics_details": "Узнайте, как оживлять машины. Программа включает изучение ROS, кинематики и обработки данных с датчиков.",
      "ai_title": "Инженерия ИИ",
      "ai_desc": "Машинное обучение, глубокое обучение, LLM, компьютерное зрение, NLP и производственные системы ИИ.",
      "ai_details": "Освойте архитектуры обучения нейросетей, работу с большими языковыми моделями (LLM) и компьютерным зрением.",
      "systems_title": "Системная инженерия",
      "systems_desc": "Проектирование сложных систем, интеграция, архитектура, верификация и крупные инженерные проекты.",
      "systems_details": "Научитесь видеть общую картину: от комплексного управления требованиями до интеграции междисциплинарных подсистем.",
      "hardware_title": "Аппаратная инженерия",
      "hardware_desc": "Проектирование пользовательских чипов, прототипирование оборудования, производство и тестирование.",
      "hardware_details": "Пройдите путь от концепции до готового устройства. Проектируйте ASIC, создавайте аппаратные прототипы и проводите тестирование."
    }
  },
  hy: {
    translation: {
      "nav_home": "Գլխավոր",
      "nav_about": "Մեր մասին",
      "nav_programs": "Ծրագրեր",
      "nav_projects": "Նախագծեր",
      "nav_contact": "Կապ",
      "nav_apply": "Դիմել հիմա",
      "footer_desc": "Առաջատար բազմամասնագիտական ինժեներական հաստատություն, որը պատրաստում է ծրագրային ապահովման, ապարատային, ռոբոտաշինության և ԱԲ ինժեներների նոր սերունդ:",
      "footer_location": "Սան Ֆրանցիսկո, Կալիֆոռնիա",
      "footer_rights": "© 2026 Ինժեներական ակադեմիա: Բոլոր իրավունքները պաշտպանված են:",
      "testi_title": "Ինչ են ասում մեր ինժեներները",
      "testi_subtitle": "Մեր շրջանավարտների հաջողության պատմությունները, ովքեր այժմ աշխատում են առաջատար ՏՏ ընկերություններում",
      "testi_sarah_role": "Ծրագրային ապահովման ինժեներ",
      "testi_sarah_text": "Գործնական նախագծերը և փորձագետների աջակցությունը ինձ վստահություն տվեցին անցնելու ավագ (senior) ինժեների պաշտոնի:",
      "testi_marcus_role": "Backend ծրագրավորող",
      "testi_marcus_text": "Լավագույն ներդրումը իմ կարիերայում: Ուսումնական ծրագիրը հենց այն է, ինչ ձեզ հարկավոր է production համակարգեր կառուցելու համար:",
      "testi_aisha_role": "Full-Stack ինժեներ",
      "testi_aisha_text": "Զրոյից մինչև իրական հավելվածների տեղակայում ամիսների ընթացքում: Ուսուցման որակն անգերազանցելի է:",
      "journey_title": "Ինժեներական ուղի",
      "journey_subtitle": "Կառուցվածքային ճանապարհ՝ սկսնակից մինչև պրոֆեսիոնալ ծրագրային ապահովման ինժեներ:",
      "step_learn_title": "Սովորել հիմունքները",
      "step_learn_desc": "Տիրապետեք ծրագրավորման հիմնական հասկացություններին, տվյալների կառուցվածքներին և ալգորիթմներին փորձագետների ուղղորդմամբ:",
      "step_build_sys_title": "Ստեղծել իրական համակարգեր",
      "step_build_sys_desc": "Կիրառեք ձեր գիտելիքները՝ մշակելով արտադրական մակարդակի հավելվածներ և ենթակառուցվածքներ:",
      "step_collab_team_title": "Թիմային համագործակցություն",
      "step_collab_team_desc": "Աշխատեք խմբային նախագծերի վրա՝ օգտագործելով արդյունաբերական ստանդարտ գործիքներ, ինչպիսիք են Git-ը, Jira-ն և Slack-ը:",
      "step_deploy_proj_title": "Նախագծերի տեղակայում",
      "step_deploy_proj_desc": "Տեղադրեք ձեր հավելվածները ամպային տիրույթում և անցեք մշակման ամբողջական կյանքի ցիկլը:",
      "step_career_supp_title": "Կարիերայի աջակցություն",
      "step_career_supp_desc": "Ստացեք ռեզյումեի վերանայում, անցեք փորձնական հարցազրույցներ և ստացեք ուղիղ կապեր գործատու գործընկերների հետ:",
      "hero_title_1": "Կերտեք ապագան",
      "hero_title_2": "Ինժեներիայի միջոցով",
      "hero_desc": "Ծրագրային ապահովումից և ԱԲ-ից մինչև էլեկտրոնիկա, ռոբոտաշինություն և առաջադեմ ապարատային համակարգեր. Ինժեներական ակադեմիան պատրաստում է համաշխարհային կարգի ինժեներների նոր սերունդ:",
      "hero_btn_join": "Միանալ հաջորդ խմբին",
      "hero_btn_explore": "Ուսումնասիրել ծրագիրը",
      "hero_console_ready": "Համակարգերը պատրաստ են",
      "about_title": "Ստեղծված է ապագա ինժեներների համար",
      "about_p1": "Ինժեներական ակադեմիան ստեղծվել է հավակնոտ ուսանողների համար, ովքեր ավելին են ուզում, քան տեսական ձեռնարկներ։ Մենք կենտրոնանում ենք խորը ինժեներական մտածողության, իրական համակարգերի և արտադրական մակարդակի զարգացման հմտությունների վրա։",
      "about_p2": "Մեր ծրագրերը նախագծված են նմանակելու իրական ծրագրային ապահովման ճարտարագիտական միջավայրը՝ համատեղելով համակարգչային գիտության հիմունքները, ժամանակակից տեխնոլոգիաները և համատեղ նախագծերի ստեղծումը։",
      "about_p3": "Մենք համագործակցում ենք ոլորտի առաջատարների հետ, որպեսզի մեր ծրագիրն արտացոլի պրոֆեսիոնալ ծրագրային ապահովման զարգացման իրական պահանջները: Յուրաքանչյուր դասախոս պրակտիկ ինժեներ է՝ արտադրության մեջ տարիների փորձով:",
      "about_p4": "Մենք պարզապես կոդ գրել չենք սովորեցնում: Մենք ինժեներներ ենք կերտում:",
      "modal_outcomes": "Կարիերայի հեռանկարներ",
      "modal_curriculum": "Դասընթացի ծրագիր",
      "modal_enroll": "Գրանցվել այս դասընթացին",
      "prog_title": "Ինժեներական ծրագրեր",
      "prog_subtitle": "Մասնագիտացված ուղղություններ՝ ձեզ ձեր ընտրած ոլորտում փորձագետ դարձնելու համար:",
      "prog_register": "Գրանցվել",
      "prog_syllabus": "Դիտել ծրագիրը",
      "course_javascript_title": "JavaScript ճարտարագիտություն",
      "course_javascript_dur": "8-9 ամիս",
      "course_javascript_desc": "Տիրապետեք ժամանակակից JavaScript-ին՝ հիմնական հասկացություններից և ES6+-ից մինչև DOM-ի առաջադեմ կառավարում և Web API-ներ:",
      "course_fullstack_title": "Full-Stack համակարգեր",
      "course_fullstack_dur": "20 Շաբաթ",
      "course_fullstack_desc": "Տիրապետեք ամբողջական ստեկին՝ տվյալների բազաների նախագծումից մինչև տեղակայում:",
      "course_devhack_title": "DevHack",
      "course_devhack_dur": "15 ամիս",
      "course_devhack_desc": "Ուսումնասիրեք ենթակառուցվածքը որպես կոդ, կոնտեյներների կառավարում և տեղակայման գործընթացներ:",
      "course_embedded_title": "Ներկառուցված համակարգեր",
      "course_embedded_dur": "18 Շաբաթ",
      "course_embedded_desc": "Մշակեք որոնվածային ծրագրեր և IoT լուծումներ սարքերի և հարթակների համար:",
      "course_ai_title": "ԱԲ (AI) ճարտարագիտություն",
      "course_ai_dur": "16 Շաբաթ",
      "course_ai_desc": "Ստեղծեք խելացի հավելվածներ մեքենայական ուսուցման և LLM-ների միջոցով:",
      "course_software_title": "Ծրագրային ճարտարագիտություն",
      "course_software_dur": "16 Շաբաթ",
      "course_software_desc": "Տիրապետեք ծրագրային ապահովման սկզբունքներին, մշակման ցիկլին, նախագծման ձևանմուշներին և agile մեթոդոլոգիաներին:",
      "course_mechanical_title": "Մեխանիկական ճարտարագիտություն",
      "course_mechanical_dur": "12-15 Շաբաթ",
      "course_mechanical_desc": "Տիրապետեք մեխանիզմների նախագծման, ջերմադինամիկայի, նյութագիտության և ժամանակակից CAD համակարգերի հիմունքներին:",
      "course_microcontroller_title": "Միկրոկոնտրոլերների հիմունքներ",
      "course_microcontroller_dur": "14-16 Շաբաթ",
      "course_microcontroller_desc": "Խորասուզվեք bare-metal ծրագրավորման, հիշողության կառավարման և միկրոկոնտրոլերների պերիֆերիայի ինտեգրման մեջ:",
      "course_electrical_title": "Էլեկտրատեխնիկա",
      "course_electrical_dur": "8 ամիս",
      "course_electrical_desc": "Ուսումնասիրեք շղթաների անալիզ, անալոգային/թվային էլեկտրոնիկա, ազդանշանների մշակում և էներգետիկ համակարգեր:",
      "course_digital_logic_title": "Թվային տրամաբանություն",
      "course_digital_logic_dur": "12 Շաբաթ",
      "course_digital_logic_desc": "Սովորեք թվային ապարատային համակարգերի հիմունքները՝ բուլյան հանրահաշվից մինչև բարդ հաջորդական շղթաներ:",
      "course_fpga_title": "FPGA ճարտարագիտություն",
      "course_fpga_dur": "2 ամիս",
      "course_fpga_desc": "Նախագծեք և սիմուլյացրեք բարձր արտադրողականության թվային համակարգեր FPGA-ների միջոցով:",
      "course_hardware_title": "Ապարատային ճարտարագիտություն",
      "course_hardware_dur": "16 Շաբաթ",
      "course_hardware_desc": "Տիրապետեք սարքավորումների ստեղծման ցիկլին՝ սխեմաների նախագծումից և PCB գծագրումից մինչև արտադրություն:",
      "how_title": "Ինչպես ենք մենք դասավանդում",
      "how_subtitle": "Մեր մեթոդաբանությունը համատեղում է տեսական հիմքերը ինտենսիվ գործնական փորձի հետ՝ արտացոլելով, թե ինչպես են աշխատում պրոֆեսիոնալ ինժեներները առաջատար ՏՏ ընկերություններում:",
      "step_theory_title": "Սովորիր հիմնական տեսությունը",
      "step_theory_desc": "Տիրապետեք հիմնարար հասկացություններին փորձագետների դասախոսությունների, ընթերցանության նյութերի և ինտերակտիվ սեմինարների միջոցով:",
      "step_labs_title": "Գործնական աշխատանք լաբորատորիաներում",
      "step_labs_desc": "Կիրառեք գիտելիքները ուղղորդված կոդավորման լաբորատորիաներում՝ անմիջական արձագանքներով և գործնական վարժություններով:",
      "step_build_title": "Ստեղծիր իրական համակարգեր",
      "step_build_desc": "Մշակեք արտադրական մակարդակի հավելվածներ՝ օգտագործելով արդյունաբերության ստանդարտ գործիքներ և լավագույն փորձը:",
      "step_collab_title": "Թիմային համագործակցություն",
      "step_collab_desc": "Աշխատեք agile թիմերում՝ օգտագործելով Git, կոդի վերանայում և զարգացման պրոֆեսիոնալ գործընթացներ:",
      "step_deploy_title": "Նախագծերի տեղակայում",
      "step_deploy_desc": "Տեղադրեք հավելվածները ամպային տիրույթում՝ անցնելով ծրագրային ապահովման մշակման ամբողջական ցիկլը:",
      "step_career_title": "Պատրաստվիր կարիերային",
      "step_career_desc": "Ստացեք աջակցություն ռեզյումեի հարցում, անցեք փորձնական հարցազրույցներ և միացեք մեր գործընկերների ցանցին:",
      "contact_title": "Սկսեք ձեր ուղին",
      "contact_subtitle": "Դիմեք հիմա կամ կապվեք մեզ հետ ծրագրերի մասին ավելին իմանալու համար",
      "contact_name_label": "Անուն Ազգանուն",
      "contact_name_placeholder": "Արամ Արամյան",
      "contact_email_label": "Էլ․ հասցե",
      "contact_email_placeholder": "aram@example.com",
      "contact_goals_label": "Ձեր նպատակները և փորձը",
      "contact_goals_placeholder": "Պատմեք մեզ ձեր ծրագրավորման փորձի և կարիերայի նպատակների մասին...",
      "contact_submit": "Ներկայացնել հայտը",
      "contact_or_google": "Կամ գրանցվեք անմիջապես Google Form-ի միջոցով",
      "contact_google_btn": "Բացել գրանցման ձևը",
      "contact_or_direct": "Կապվեք մեզ հետ անմիջապես",
      "contact_telegram": "Telegram",
      "contact_whatsapp": "WhatsApp",
      "showcase_title": "Բազմամասնագիտական նախագծեր",
      "showcase_subtitle": "Իրական ինժեներական համակարգեր, որոնք կառուցվել են մեր ուսանողների կողմից՝ ընդգրկելով ծրագրային, ապարատային, ռոբոտաշինության, ԱԲ և ներկառուցված համակարգեր",
      "proj_robot_title": "Ինքնավար առաքման ռոբոտ",
      "proj_robot_cat": "Ռոբոտաշինություն + ԱԲ (AI)",
      "proj_iot_title": "Խելացի IoT էներգետիկ համակարգ",
      "proj_iot_cat": "Ներկառուցված + Ապարատային",
      "proj_dashboard_title": "ԱԲ-ի վրա հիմնված վահանակ",
      "proj_dashboard_cat": "Ծրագրային ապահովում + ԱԲ (AI)",
      "proj_drone_title": "Անօդաչու թռչող սարքի կարգավորիչ",
      "proj_drone_cat": "Ներկառուցված + Ռոբոտաշինություն",
      "proj_monitor_title": "Արդյունաբերական մոնիտորինգի հարթակ",
      "proj_monitor_cat": "Համակարգային ճարտարագիտություն",
      "proj_fpga_title": "Հատուկ FPGA պրոցեսոր",
      "proj_fpga_cat": "Ապարատային ճարտարագիտություն",
      "proj_arm_title": "Ռոբոտային ձեռքի կարգավորիչ",
      "proj_arm_cat": "Մեխանիկական + Ծրագրային ապահովում",
      "proj_hub_title": "Խելացի տան հանգույց (Hub)",
      "proj_hub_cat": "Էլեկտրական + IoT",
      "proj_chat_title": "LLM Չաթ հավելված",
      "proj_chat_cat": "ԱԲ ճարտարագիտություն",
      "metric_engineers": "Ուսուցանված ինժեներներ",
      "metric_disciplines": "Ուղղություններ",
      "metric_projects": "Ստեղծված նախագծեր",
      "metric_placement": "Աշխատանքի տեղավորում",
      "labs_badge": "Հետազոտական մակարդակի ենթակառուցվածք",
      "labs_title": "Լաբորատորիաներ և հարմարություններ",
      "labs_subtitle": "Ժամանակակից լաբորատորիաներ և ինժեներական աշխատանքային տարածքներ՝ նախատեսված նորարարության, համագործակցության և տեխնիկական զարգացման համար:",
      "labs_footer_text": "Բոլոր ուսանողները ստանում են շուրջօրյա (24/7) մուտք դեպի պրոֆեսիոնալ սարքավորումներ և լաբորատորիաներ:",
      "labs_btn_tour": "Գրանցվել էքսկուրսիայի",
      "lab_ai_name": "ԱԲ հաշվողական լաբորատորիա",
      "lab_ai_desc": "Բարձր արտադրողականության GPU կլաստերներ խորը ուսուցման, LLM վերապատրաստման և ԱԲ առաջադեմ հետազոտությունների համար:",
      "lab_robotics_name": "Ռոբոտաշինության լաբորատորիա",
      "lab_robotics_desc": "Արդյունաբերական ռոբոտային ձեռքեր, ինքնավար տրանսպորտային միջոցներ, անօդաչու թռչող սարքեր և շարժման գրանցման համակարգեր:",
      "lab_electronics_name": "Էլեկտրոնիկայի լաբորատորիա",
      "lab_electronics_desc": "Օսցիլոսկոպներ, ազդանշանների գեներատորներ, PCB արտադրություն և ճշգրիտ չափման սարքավորումներ:",
      "lab_embedded_name": "Ներկառուցված համակարգեր",
      "lab_embedded_desc": "STM32, FPGA տախտակներ, տրամաբանական անալիզատորներ և IoT նախատիպերի ստեղծման կայաններ:",
      "lab_mechanical_name": "Մեխանիկական արհեստանոց",
      "lab_mechanical_desc": "3D տպիչներ, CNC հաստոցներ, CAD կայաններ և ճշգրիտ արտադրության գործիքներ:",
      "lab_studios_name": "Համագործակցային ստուդիաներ",
      "lab_studios_desc": "Թիմային նախագծերի տարածքներ՝ գրատախտակներով, վիդեոկոնֆերանսներով և agile մշակման գործիքներով:",
      "phil_mission": "Մեր առաքելությունը",
      "phil_title": "Ինժեներական փիլիսոփայություն",
      "phil_desc1": "Մենք հավատում ենք, որ ինժեներիան ավելին է, քան կոդ գրելը կամ սխեմաներ նախագծելը: Դա մտածելակերպ է՝ համակարգված մոտեցում բարդությունները հասկանալու, լուծումներ ստեղծելու և ապագան կերտելու համար:",
      "phil_desc2": "Ինժեներական ակադեմիայում մենք պատրաստում ենք ուսանողներին դառնալու վաղվա տեխնոլոգիաների ճարտարապետներ՝ համատեղելով խորը տեխնիկական վարպետությունը ստեղծագործական խնդիրների լուծման և միջդիսցիպլինար համագործակցության հետ:",
      "phil_cta_title": "Միացեք ինժեներների նոր սերնդին",
      "phil_cta_desc": "Անկախ նրանից, թե դուք հետաքրքրված եք ծրագրավորմամբ, էլեկտրոնիկայով, ռոբոտաշինությամբ կամ ԱԲ-ով, մենք կօգնենք ձեզ վերածել այդ կիրքը համաշխարհային մակարդակի ինժեներական փորձի:",
      "phil_btn_apply": "Դիմել հիմա",
      "phil_btn_download": "Ներբեռնել ծրագիրը",
      "prin_think_title": "Մտածիր որպես ինժեներ",
      "prin_think_desc": "Զարգացրեք խնդիրների համակարգված լուծում, քննադատական մտածողություն և հիմնարար սկզբունքների վրա հիմնված տրամաբանություն:",
      "prin_build_title": "Ստեղծիր Production համակարգեր",
      "prin_build_desc": "Ստեղծեք իրական լուծումներ, որոնք համապատասխանում են արդյունաբերական ստանդարտներին և մասնագիտական պահանջներին:",
      "prin_integrate_title": "Միավորիր Սարքավորումներ + Ծրագրեր",
      "prin_integrate_desc": "Տիրապետեք ամբողջական ինժեներական ստեկին՝ ներկառուցված որոնվածից մինչև ամպային ենթակառուցվածք:",
      "prin_solve_title": "Լուծիր իրական խնդիրներ",
      "prin_solve_desc": "Աշխատեք կարևոր նախագծերի վրա՝ լուծելով արդի տեխնիկական և ոլորտային մարտահրավերներ:",
      "prin_collab_title": "Համագործակցիր այլ ոլորտների հետ",
      "prin_collab_desc": "Ստացեք բազմամասնագիտական թիմային աշխատանքի փորձ, որն արտացոլում է ժամանակակից ինժեներական կազմակերպությունները:",
      "prin_innovate_title": "Խթանիր նորարարությունը",
      "prin_innovate_desc": "Ընդլայնեք սահմանները, փորձարկեք նորագույն տեխնոլոգիաներ և ձևավորեք ապագան:",
      "why_title": "Ինչու՞ ընտրել մեզ",
      "why_subtitle": "Ինժեներական կրթության համապարփակ մոտեցում, որը ձեզ նախապատրաստում է իրական աշխատանքին:",
      "feat_curriculum_title": "Ինտենսիվ ուսումնական ծրագիր",
      "feat_curriculum_desc": "Արդյունաբերությանը համապատասխան դասընթացներ՝ մշակված ավագ ինժեներների կողմից՝ գործնական հմտություններ ձևավորելու համար:",
      "feat_projects_title": "Իրական նախագծեր",
      "feat_projects_desc": "Ստեղծեք և տեղակայեք իրական համակարգեր՝ բաշխված backend-ներից մինչև ԱԲ հարթակներ՝ հավաքելով հզոր պորտֆոլիո:",
      "feat_mentors_title": "Փորձառու մենթորներ",
      "feat_mentors_desc": "Սովորեք առաջատար ՏՏ ընկերությունների փորձառու ինժեներներից, ովքեր տրամադրում են անհատականացված ուղղորդում և կոդի վերանայում:",
      "how_cta_title": "Զգացեք Ինժեներական ակադեմիայի տարբերությունը",
      "how_cta_desc": "Մեր ապացուցված մեթոդաբանությունը օգնել է ավելի քան 150 ուսանողների հաջողությամբ սկսել ինժեներական կարիերա Google, Meta, Amazon ընկերություններում և նորարարական ստարտափներում ամբողջ աշխարհում:",
      "how_cta_btn": "Սկսեք ձեր ուղին այսօր",
      "val_exc_title": "Ինժեներական գերազանցություն",
      "val_exc_desc": "Մենք հավատում ենք խորը տեխնիկական վարպետությանը, ոչ թե մակերեսային ձեռնարկներին: Յուրաքանչյուր դաս ձևավորում է իրական ինժեներական մտածողություն:",
      "val_prod_title": "Ուսուցում արտադրության միջոցով",
      "val_prod_desc": "Ուսանողներն առաջին իսկ օրվանից աշխատում են իրական համակարգերի վրա՝ անցնելով ծրագրային ապահովման մշակման ամբողջական կյանքի ցիկլը:",
      "val_inno_title": "Նորարարական մոտեցում",
      "val_inno_desc": "Մենք դասավանդում ենք նորագույն տեխնոլոգիաներ և մեթոդոլոգիաներ, որոնք օգտագործվում են աշխարհի առաջատար ՏՏ ընկերությունների կողմից:",
      "val_cult_title": "Համագործակցային մշակույթ",
      "val_cult_desc": "Թիմային նախագծերը, կոդի վերանայումները (code review) և զույգով ծրագրավորումը արտացոլում են պրոֆեսիոնալ ինժեներական միջավայրը:",
      "title": "Ինժեներական մասնագիտություններ",
      "description": "Տիրապետեք ժամանակակից ինժեներիայի ամբողջ սպեկտրին՝ ծրագրավորումից և էլեկտրոնիկայից մինչև ռոբոտաշինություն, ԱԲ և ապարատային համակարգեր:",
      "explore": "Ուսումնասիրել ծրագիրը",
      "overview": "Ծրագրի մանրամասն ակնարկ",
      "about": "Ծրագրի մասին",
      "technologies": "Հիմնական տեխնոլոգիաներ",
      "close": "Փակել",
      "software_title": "Ծրագրային ճարտարագիտություն",
      "software_desc": "Full-stack համակարգեր, backend ճարտարապետություն, ամպային ենթակառուցվածքներ, ԱԲ համակարգեր:",
      "software_details": "Այս ծրագրում դուք կուսումնասիրեք մասշտաբային համակարգերի նախագծում, տվյալների բազաների կառավարում և միկրոսերվիսային ճարտարապետություն:",
      "electrical_title": "Էլեկտրատեխնիկա",
      "electrical_desc": "Անալոգային և թվային էլեկտրոնիկա, PCB դիզայն, ազդանշանների մշակում և էներգահամակարգեր:",
      "electrical_details": "Ծրագիրն ընդգրկում է էլեկտրոնիկայի ստեղծման ամբողջ ցիկլը՝ SPICE-ում շղթաների սիմուլյացիայից մինչև բազմաշերտ PCB երթուղավորում:",
      "mechanical_title": "Մեխանիկական ճարտարագիտություն",
      "mechanical_desc": "CAD համակարգեր, ռոբոտաշինության մեխանիկա, արտադրություն, ջերմադինամիկա և աերոտիեզերական ինժեներիա:",
      "mechanical_details": "Տիրապետեք մեխանիզմների նախագծման սկզբունքներին, վերջավոր տարրերի անալիզին (FEA) և արտադրության ժամանակակից մեթոդներին:",
      "embedded_title": "Ներկառուցված համակարգեր",
      "embedded_desc": "STM32, միկրոկոնտրոլերներ, FPGA համակարգեր, IoT սարքեր, որոնվածի մշակում և սենսորների ինտեգրում:",
      "embedded_details": "Խորասուզվեք միկրոկոնտրոլերների ծրագրավորման մեջ C/C++ լեզվով, աշխատեք RTOS-ի հետ և նախագծեք FPGA ճարտարապետություններ:",
      "robotics_title": "Ռոբոտաշինություն",
      "robotics_desc": "Ավտոնոմ համակարգեր, շարժման վերահսկում, համակարգչային տեսլական և ԱԲ-ով աշխատող ռոբոտաշինություն:",
      "robotics_details": "Իմացեք, թե ինչպես կյանքի կոչել մեքենաները: Ծրագիրը ներառում է ROS-ի, կինեմատիկայի և տվյալների մշակման ուսումնասիրություն:",
      "ai_title": "ԱԲ ճարտարագիտություն",
      "ai_desc": "Մեքենայական ուսուցում, խորը ուսուցում, LLM, համակարգչային տեսլական, NLP և ԱԲ արտադրական համակարգեր:",
      "ai_details": "Տիրապետեք նեյրոնային ցանցերի ուսուցման ճարտարապետությանը, աշխատեք LLM-ների և համակարգչային տեսլականի հետ:",
      "systems_title": "Համակարգային ճարտարագիտություն",
      "systems_desc": "Բարդ համակարգերի նախագծում, ինտեգրում, ճարտարապետություն, ստուգում և խոշոր ինժեներական նախագծեր:",
      "systems_details": "Սովորեք տեսնել մեծ պատկերը՝ պահանջների համապարփակ կառավարումից մինչև ենթահամակարգերի ինտեգրում:",
      "hardware_title": "Ապարատային ճարտարագիտություն",
      "hardware_desc": "Պատվերով չիպերի նախագծում, ապարատային նախատիպեր, արտադրություն, փորձարկում և արտադրանքի ինժեներիա:",
      "hardware_details": "Անցեք հայեցակարգից մինչև պատրաստի սարք: Նախագծեք պատվերով սիլիցիում (ASIC), ստեղծեք նախատիպեր և անցկացրեք փորձարկումներ:"
    }
  }
};

i18n
  .use(initReactI18next)
  .init({
    resources,
    lng: "en", 
    fallbackLng: "en", 
    interpolation: {
      escapeValue: false 
    }
  });

export default i18n;